modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"
[[mods]] #mandatory
modId="advance_food" #mandatory
version="1.0.0" #mandatory
displayName="Example Mod" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="bg.png" #optional
credits="All The Credits Goes To LakshyaK2011"
authors="LakshyaK2011"
description='''
    This is Advance
'''
[[dependencies.advance_food]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[39,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.advance_food]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
